### ISSUE TITLE
Error with compiling

### ISSUE THREAD

**Issue by shuntos** [AlexeyAB/Yolo_mark#57]
ubuntu 16.04 ,python 3.6 ,opencv 3
I got following error while compiling 
sepal@sepal-MS-7A74:~/Yolo_mark$ make
Scanning dependencies of target yolo_mark
[ 50%] Building CXX object CMakeFiles/yolo_mark.dir/main.cpp.o
/home/sepal/Yolo_mark/main.cpp:16:31: fatal error: opencv2/highgui.hpp: No such file or directory
compilation terminated.
CMakeFiles/yolo_mark.dir/build.make:62: recipe for target 'CMakeFiles/yolo_mark.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/yolo_mark.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/yolo_mark.dir/all' failed
make[1]: *** [CMakeFiles/yolo_mark.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by AlexeyAB** [comment]
Try to change this line: https://github.com/AlexeyAB/Yolo_mark/blob/0fb2f84fd77488e48d22c7ba30e23eafabdf09f9/main.cpp#L16
to this
`#include <opencv2/highgui/highgui.hpp>`

Can it help you?

**Comment by shuntos** [comment]
It didn't work

**Comment by shuntos** [comment]
Thanks , it worked fine

**Comment by AlexeyAB** [comment]
I fixed it in the source code.

**Comment by vivek6449** [comment]
I am still getting this error. 
Ubuntu 16.04 OpenCV 3.1.0 Python 3.6.5

[ 50%] Building CXX object CMakeFiles/yolo_mark.dir/main.cpp.o
/home/vivek/Desktop/Rotor crack detection/Yolo Annotation/Yolo_mark/main.cpp: In function ‘int main(int, char**)’:
/home/vivek/Desktop/Rotor crack detection/Yolo Annotation/Yolo_mark/main.cpp:150:23: error: ‘waitKeyEx’ is not a member of ‘cv’
     int pressed_key = cv::waitKeyEx(20); // OpenCV 3.x
                       ^
/home/vivek/Desktop/Rotor crack detection/Yolo Annotation/Yolo_mark/main.cpp:644:22: error: ‘waitKeyEx’ is not a member of ‘cv’
    int pressed_key = cv::waitKeyEx(20); // OpenCV 3.x
                      ^
CMakeFiles/yolo_mark.dir/build.make:62: recipe for target 'CMakeFiles/yolo_mark.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/yolo_mark.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/yolo_mark.dir/all' failed
make[1]: *** [CMakeFiles/yolo_mark.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by AlexeyAB** [comment]
@vivek6449 

Try to add at the top of `main.cpp` file this line: 
`#include <opencv2/highgui.hpp>`

If it doesn't help, then try to change in this two line `waitKeyEx` to `waitKey`
1. https://github.com/AlexeyAB/Yolo_mark/blob/5082b30c51b13dbef4da1f8b407997a5320da267/main.cpp#L150
2.  https://github.com/AlexeyAB/Yolo_mark/blob/5082b30c51b13dbef4da1f8b407997a5320da267/main.cpp#L644

**Comment by kanza-ali** [comment]
@AlexeyAB 

I have tried all the above solutions but I have the same error. 

![yolomarkerror](https://user-images.githubusercontent.com/33715985/48698063-7e34bd80-ec29-11e8-8b33-0d4d11f9b8ee.png)
